### ISSUE TITLE
Duplication of mob in teleport

### ISSUE THREAD

**Issue by DjeyMute** [SpaicyGaming/UpgradablesPets#15]
Hello,
When we tp to a player the pet stays in place and becomes an animal that no longer belongs to us.
It should be ensured that when a player is tp the pet must have gone away.
And also add an option to remove the possibility for players to hit the pets.

**Comment by SpaicyGaming** [comment]
Can you send me the output of "/ver"? 
Does it only happen when players are in different worlds?

Thanks for the suggestion, I'll implement this feature in the next update.

**Comment by DjeyMute** [comment]
In the same world too.

**Comment by DjeyMute** [comment]
And also when a pet dies if the player redeems a pet in that his first fart died then his also created a duplication bug on the first fart.

**Comment by DjeyMute** [comment]
Can you fix this fast enough?

**Comment by SpaicyGaming** [comment]
I'm sorry you waited soo long to use it in 1.14.4. I develop this minecraft plugin in my free time, as a hobby. 

I can't replicate the pet duplication issue. I think that's caused by a conflict with another plugin on your server. Anyway, I've increased the "teleport priority". Please let me know if you still experience this issue.

I've implemented new configuration options to toggle whether players can hit others' pets. Thank you for the suggestion  :)

The whole plugin assumes players can have only one pet each. I don't plan to allow players to own more than one pet shortly. I'll add this option in the future.
