### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by DjeyMute** [SpaicyGaming/UpgradablesPets#5]
Hello,
Can you add a command for give a pet to a player ?
For exemple : /pet give <player> <nameofpet>

Thanks.

**Comment by DjeyMute** [comment]
Ans I would also like to ask you if it would be possible to add in the config the number of blocks that can be between the player and his animal ?

**Comment by SpaicyGaming** [comment]
Thank you for the suggestion, I'll implement that feature in the next update.

Can you better explain what do you mean with "add in the config the number of blocks that can be between the player and his animal"? Pets follow their owners at a specific speed. When the owner is too distant (for example because he has been teleported), the pet gets teleported at his owner's location.

**Comment by SpaicyGaming** [comment]
Features added in the release [2.2.0-DEV](https://www.spigotmc.org/resources/upgradablespets-1-7-1-13-x-mysql-mongodb-levels-guis-effects.46406/update?update=264720)
